code/modules/vtmb/jobs/doctor.dm
code/modules/vtmb/jobs/police.dm

Каитиффы могут заходить за Директора Больницы. Гули могут заходить за Шефа Полиции.
Людишки желают.
:cl:
add: Возможность каитиффам заходить за главу больницы
add: Возможность гулям заходить за шефа полиции
/:cl:

Каитифф теперь может лечить людей, шеф стал Канеки

---

code/modules/client/preferences.dm

*Ghouls should have specific disciplines

---

code/modules/vtmb/chi_disciplines.dm

Сделал как по книжке, чтобы синтай плоти тратил янь ци, вместо инь.

chi_disciplines.dm

---

code/modules/vtmb/rolling.dm

Чиним ошибку VS Code
Да заебал бля твинер
<details>
</details>
:cl:
fix: Запятая в цитатах шиза
/:cl:

Блять запятую проебали

---

code/__DEFINES/discipline.dm
code/__DEFINES/span.dm
code/__DEFINES/traits/vtm/declarations.dm
code/__DEFINES/traits/vtm/sources.dm
code/__HELPERS/unsorted.dm
code/datums/status_effects/buffs.dm
code/game/objects/effects/glowshroom.dm
code/modules/mob/living/living_defines.dm
code/modules/vtmb/disciplines/_disc_power.dm
code/modules/vtmb/disciplines/thaumaturgy.dm
code/modules/vtmb/jobs/hunter.dm
code/modules/vtmb/jobs/national_guard.dm
code/modules/vtmb/jobs/sabbat.dm
code/modules/vtmb/jobs/swat.dm
code/modules/vtmb/magic/pyramid.dm
code/modules/wod13/bloodsucking.dm
tgstation.dme

Реворкает тауму ебанный бляяя
Че то там лор апдейт
<details>
</details>
:cl:
add: Добавил крафт тома тремеров
add: Добавил флаги на дисцы разные
add: Переделана таума
/:cl:

Таума реворк

---

code/modules/vtmb/dharma.dm

Пока что...
Исправил (наверное) ошибку в коде, из-за которой дракон не смог получить третье условие дхармы.
Теперь его дхарма работает, как задумывал Флав (пока что).
Твинер, потом испытаем.

Драконы теперь точно должны куколдить над чужими смертями.

---

code/modules/jobs/jobs.dm
code/modules/mob/dead/new_player/latejoin_menu.dm
code/modules/mob/dead/new_player/new_player.dm
code/modules/tgui/states/new_player.dm
tgstation.dme
tgui/packages/tgui/interfaces/LatejoinMenu.jsx

Обновил UI входа в игру после старта:
Красиво
<details>
Нет здесь ничего
</details>
:cl:
add: Добавил новый интерфейс для UI Late Join Menu
fix: Исправил состояние нового игрока: теперь не учитывается то, что игрок - админ
/:cl:

Переработка меню входа в игру

---

code/modules/client/preferences_tabs/Char_settings and Charlist.dm

Цены не соответствовали действительности, теперь соответствуют
Багфикс
<details>
</details>
:cl:
fix: Фикс отображения цен дисциплин
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
map: added/modified/removed map content
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Фикс отображения цен дисциплин

---

code/modules/client/preferences.dm

Название
Циферки стоимости были не те
<details>
</details>
:cl:
fix: Фикс стоимости дисциплин
/:cl:

Фикс стоимости дисциплин

---

code/modules/mob/dead/new_player/new_player.dm
code/modules/mob/dead/observer/observer.dm

Заменил обычные инпуты на TGUI инпуты для кнопок гостоты
Красиво
<details>
</details>

Обновил инпуты для гостоты

---

.github/workflows/gbp.yml
.github/workflows/gbp_collect.yml

Включил автолейблер в CI
<details>
</details>
:cl:
add: Включил авто-лейблер в CI
/:cl:

Включил автолейблер в CI

---

.github/workflows/gbp.yml
.github/workflows/gbp_collect.yml

Reverts Discozavisim/World-of-Darkness-13#124

Revert "Включил автолейблер в CI"

---

code/datums/map_config.dm

Пофиксил проблему с тем, что Умбра не загружалась
Это фикс потому что
<details>
</details>
:cl: FeudeyTF
fix: Умбра теперь загружается
/:cl:

Исправил ошибку с тем, что умбра не загружалась

---

code/modules/wod13/decor.dm

Исправил баг, что при выходе через матрицу записи об игроки оставались в манифесте. Теперь записи удаляются и игрок перестаёт отображаться в манифесте.
Это фикс
<details>
</details>
:cl: FeudeyTF
fix: Пофиксил повторные записи в манифесте
/:cl:

Исправление бага с записями в манифесте после выхода из игры

---

bin/build.cmd
bin/clean.cmd
bin/server.cmd
bin/test.cmd
bin/tgfont.cmd
bin/tgui-bench.cmd
bin/tgui-build.cmd
bin/tgui-dev.cmd
bin/tgui-sonar.cmd

Портировал с tg/station скрипты для быстрого доступа к разных функция билд скрипта, таким как очитка, дев-сервер и т.д.
Удобно
<details>
</details>
:cl: FeudeyTF
add: Портировал скрипты для быстрого доступа к функциям файла сборки проекта
/:cl:

Портировал скрипты для tools/build/build.bat

---

.github/workflows/compile_changelogs.yml

Попытка исправить компиляцию всех журналов изменений
<details>
</details>

Попытка исправить компиляцию всех журналов изменений

---

code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm

Стаи летучей мыши
<details>
</details>
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
map: added/modified/removed map content
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Летучие мышки

---

.github/workflows/gbp.yml
.github/workflows/gbp_collect.yml

Reverts Discozavisim/World-of-Darkness-13#125

Revert "Revert "Включил автолейблер в CI""

---

code/modules/client/preferences_savefile.dm

Забыл говно в бд внести
Ну круто ведь что не проебываешь статы и экспу
:cl:
fix: Фикс специализации атрибутов
/:cl:

Фикс специализации атрибутов

---

code/modules/vtmb/jobs/supply_assistant.dm
code/modules/wod13/blackout.dm

Рейдж фикс и блять ролька саппли технишн открыта гару
Ну сука не хочу ебать все и вся плюс хочу ящички таскать бубенчики
:cl:
add: Теперь надо 8 рейджа чтобы был шанс впасть на ярость. Пассивно можно получить только 7
add: Гару могут играть за Supply Technician
/:cl:

Фикс рейджа и сапли технишн фурри
